<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="HomeWork1" duration-ms="30090" started-at="2017-10-25T18:06:41Z" finished-at="2017-10-25T18:07:11Z">
    <groups>
    </groups>
    <test name="Regression2" duration-ms="30090" started-at="2017-10-25T18:06:41Z" finished-at="2017-10-25T18:07:11Z">
      <class name="firstHomeWork.LoginTest">
        <test-method status="PASS" signature="beforeTheTest()[pri:0, instance:firstHomeWork.LoginTest@50dfbc58]" name="beforeTheTest" is-config="true" duration-ms="2986" started-at="2017-10-25T21:06:38Z" finished-at="2017-10-25T21:06:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTheTest -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:firstHomeWork.LoginTest@50dfbc58]" name="loginTest" duration-ms="8449" started-at="2017-10-25T21:06:41Z" data-provider="correctLoginData" finished-at="2017-10-25T21:06:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[webinar.test@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Xcg7299bnSmMuRLp9ITw]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:firstHomeWork.LoginTest@50dfbc58]" name="loginTest" duration-ms="7089" started-at="2017-10-25T21:06:50Z" data-provider="correctLoginData" finished-at="2017-10-25T21:06:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[webinar.test@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Xcg7299bnSmMuRLp9ITw]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:firstHomeWork.LoginTest@50dfbc58]" name="loginTest" duration-ms="6664" started-at="2017-10-25T21:06:57Z" data-provider="correctLoginData" finished-at="2017-10-25T21:07:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[webinar.test@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Xcg7299bnSmMuRLp9ITw]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="testIncorrectDataForLogging(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:firstHomeWork.LoginTest@50dfbc58]" name="testIncorrectDataForLogging" duration-ms="2990" started-at="2017-10-25T21:07:04Z" data-provider="incorrectLoginData" finished-at="2017-10-25T21:07:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[webinar.test@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Xcg7299bnSmMuRLp9ITw1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Неверный пароль]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: a string containing "НЕВЕРНЫЙ ПАРОЛЬ"
     but: was "ТАКОГО РАБОТНИКА НЕТ ИЛИ ПАРОЛЬ УКАЗАН НЕВЕРНО."]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: a string containing "НЕВЕРНЫЙ ПАРОЛЬ"
     but: was "ТАКОГО РАБОТНИКА НЕТ ИЛИ ПАРОЛЬ УКАЗАН НЕВЕРНО."
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at utilsAndHelpers.HelpersMethod.assertContains(HelpersMethod.java:100)
	at firstHomeWork.LoginMethod.testIncorrectDataForLogging(LoginMethod.java:36)
	at firstHomeWork.LoginTest.testIncorrectDataForLogging(LoginTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIncorrectDataForLogging -->
        <test-method status="PASS" signature="testIncorrectDataForLogging(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:firstHomeWork.LoginTest@50dfbc58]" name="testIncorrectDataForLogging" duration-ms="2930" started-at="2017-10-25T21:07:07Z" data-provider="incorrectLoginData" finished-at="2017-10-25T21:07:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[weebinar.test@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Xcg7299bnSmMuRLp9ITw]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Такого работника нет или пароль указан неверно.]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIncorrectDataForLogging -->
        <test-method status="PASS" signature="afterTests()[pri:0, instance:firstHomeWork.LoginTest@50dfbc58]" name="afterTests" is-config="true" duration-ms="1249" started-at="2017-10-25T21:07:10Z" finished-at="2017-10-25T21:07:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTests -->
      </class> <!-- firstHomeWork.LoginTest -->
    </test> <!-- Regression2 -->
  </suite> <!-- HomeWork1 -->
</testng-results>
